name: Daily Commit

on:
  schedule:
    - cron: '00 06 * * *'
    - cron: '00 09 * * *'
    - cron: '00 11 * * *'
    - cron: '00 08 * * *'
    - cron: '00 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Dynamic Commits by Day
        run: |
          # 1. Obtener día (1=Lun, 2=Mar, 3=Mie, 4=Jue, 5=Vie, 6=Sab, 7=Dom)
          DAY=$(date +%u)

          # 2. Definir límites: [0, Lun, Mar, Mie, Jue, Vie, Sab, Dom]
          # Ponemos 0 en el índice cero para que el 1 sea Lunes
          LIMITS=(0 5 3 6 10 12 1 1)
          
          # 3. Obtener el número de commits para hoy
          CANTIDAD=${LIMITS[$DAY]}
          
          echo "Hoy es día $DAY, se realizarán $CANTIDAD commits."

          # 4. Configurar Git una sola vez
          git config user.name "luthors"
          git config user.email "luis.g.toro@gmail.com"

          # 5. Bucle para crear los commits solicitados
          for ((i=1; i<=$CANTIDAD; i++))
          do
            echo "Update $i/$CANTIDAD: $(date)" >> log.txt
            git add log.txt
            git commit -m "Auto update $i/$CANTIDAD - $(date)" || echo "No hay cambios"
          done

          # 6. Subir todos los commits juntos
          git push
